### ISSUE TITLE
Update plugin information

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/edd-taxjar#13]
Quite a bit needs to be updated in this plugin:
- The Author and Author URI (plugin header)
- Plugin URI (plugin header), currently a 404
- Tested up to version (readme.txt)
- Donate link (readme.txt)...we do have an official one: https://easydigitaldownloads.com/donate/

**Comment by LisaCee** [comment]
PR #15 Updates author, links, and spelling
